Blog app - integration specs for views
er-contreras/Blog_Application pull request #13
Opened 2021-12-10 15:44 UTC by tiagorahal

### In this PR we added capybara testing for views
 - Added tests for login
 - Added tests for user index
 - Added tests for user show
 - Added tests for post index
 - Added tests for post show

2021-12-10 16:04 UTC, mke2111 requested changes
### Hey @tiagorahal & @eri8-9, 

**This is a great project you have going on, well-done lads**. 

   
**However, there are a few sections to improve before your project is approved.** 🔴 
<hr>

## Required Changes ♻️

- [x] In the readme file, add step-by-step instructions on how to set up your app on a computer locally. Remember to include all the necessary commands to run in the terminal

_Check the inline comments under the review for sections to improve._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-10 16:07 UTC, mke2111 commented on spec/views/user_show_spec.rb
> +  end
Great job adding these test cases. However, let us add these remaining test cases to sum it up all.

- [ ] Add a test that asserts you can see the user's first 3 posts.
- [ ] Add a test that asserts you can see a button that lets me view all of a user's posts.
- [ ] Add a test that redirects to the user's post's index page when you click on a see all posts.

2021-12-10 16:10 UTC, mke2111 commented on spec/views/post_index_spec.rb
> +  end
Let us add these test cases for the post index.

- [ ] Add a test that asserts you can see how many comments a post has.
- [ ] Add a test that asserts you can see how many likes a post has.

2021-12-10 16:13 UTC, mke2111 commented on spec/views/post_show_spec.rb
> +  end
Again, lets add these tests to cater for all scenarios.

- [ ] Add a test that asserts you can see how many comments the post has.
- [ ] Add a test that asserts you can see how many likes the post has.
- [ ] Add a test that asserts you can see the username of each commentor.

2021-12-10 22:58 UTC, rloterh approved these changes
## Status: Approved :heavy_check_mark:

Hi Tiago, 

Your project is complete! Great job for making the necessary changes recommended in the previous review. There is nothing else to say other than... it's time to merge it 🍾 :shipit:. Congratulations! 🎉🥂

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

_Kindly consider my comment(s) marked **[OPTIONAL]** under this review:_
<br>
Cheers and Happy coding!👏 💻 🍷 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 1 more limited review per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2021-12-10 22:58 UTC, rloterh commented on README.md
> +
- [ ] OPTIONAL
Kindly include in your ReadMe a step-by-step approach to run your test cases. This will make your ReadMe appear more professional

2021-12-11 00:40 UTC, merged

2021-12-11 15:08 UTC, henatan99 reviewed
Hi @tiagorahal , 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has already an approved status. 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._